kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
files:
  - file: dev/public/*
    attributes:
      release: dev
  - file: prod/public/*
    attributes:
      release: prod
  - file: "*/public/images/*"
    attributes:
      type: image
  - file: "*/themes/anake"
    attributes:
      theme: anake
  - file: "*/themes/PaperMod"
    attributes:
      theme: PaperMod